version: '3.8'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - /home/ec2-user/docker/mysql/conf:/etc/mysql/conf.d
      - /home/ec2-user/docker/mysql/lib:/var/lib/mysql
      - /home/ec2-user/docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: '0000'
    ports:
      - 3306:3306
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379