### 코스 등록
POST http://localhost:8081/course
Content-Type: application/json

{
  "title": "test title",
  "contents": "test contents",
  "status": "OPEN",
  "startAt": "2023-07-12T09:00:00",
  "endAt": "2023-07-12T12:00:00",
  "speaker": "gwKoo",
  "placeId": "1"
}